// micro-frontend/vue-sub-app/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import HelloWorld from "./components/HelloWorld.vue";

const title = ref<string>("Rspack + Vue");
</script>

<template>
  <div>
    <a href="https://www.rspack.dev/" target="_blank">
      <img src="./assets/rspack.svg" class="logo" alt="Rspack logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo" alt="Vue logo" />
    </a>
  </div>
  <HelloWorld :msg="title" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  /* transition: filter 300ms; */
}

.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}

.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// micro-frontend/app/src/App.tsx
import { useState } from "react";
import reactLogo from "./assets/react.svg";
import "./App.css";

function App() {
  const [count, setCount] = useState(0);

  return (
    <div className="App">
      <div>
        <a href="https://reactjs.org" target="_blank" rel="noreferrer">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Main App</h1>
      <div className="card">Sub App</div>
    </div>
  );
}

export default App;
